# -*- coding: utf-8 -*-
"""Kvasir_SEGPolyp_WDFF-Net.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDDrFyQeFlBYCOozfChpPhFGJhS1j2Xv
"""

!pip install -q timm albumentations segmentation-models-pytorch torchmetrics opencv-python matplotlib tqdm

# ✅ Cell 1 — Imports & setup
import os, cv2, random, numpy as np, pandas as pd, matplotlib.pyplot as plt
from glob import glob
from tqdm import tqdm

import torch, torch.nn as nn, torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import albumentations as A
import timm

# Mount Drive
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"🚀 Using device: {DEVICE}")

class KvasirDataset(Dataset):
    def __init__(self, df, size=512, augment=False):
        self.df = df.reset_index(drop=True)
        self.size = size
        self.augment = augment
        if augment:
            self.tf = A.Compose([
                A.Resize(size, size),
                A.HorizontalFlip(p=0.5),
                A.VerticalFlip(p=0.2),
                A.RandomBrightnessContrast(p=0.2),
                A.Normalize()
            ])
        else:
            self.tf = A.Compose([A.Resize(size, size), A.Normalize()])

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        r = self.df.iloc[idx]
        img_path, mask_path = r['image'], r['mask']

        if not os.path.exists(img_path) or not os.path.exists(mask_path):
            raise FileNotFoundError(f"Missing: {img_path} or {mask_path}")

        img = cv2.cvtColor(cv2.imread(img_path), cv2.COLOR_BGR2RGB)
        mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
        mask = np.expand_dims(mask, -1)

        sample = self.tf(image=img, mask=mask)
        img = sample['image'].astype('float32').transpose(2,0,1)
        mask = (sample['mask'].astype('float32') / 255.0).transpose(2,0,1)
        return torch.tensor(img), torch.tensor(mask)

class ObjectAwareAttention(nn.Module):
    def __init__(self, channels):
        super().__init__()
        self.channel_att = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),
            nn.Conv2d(channels, max(1, channels//8), 1),
            nn.ReLU(True),
            nn.Conv2d(max(1, channels//8), channels, 1),
            nn.Sigmoid()
        )
        self.spatial_conv = nn.Sequential(nn.Conv2d(2, 1, 3, padding=1), nn.Sigmoid())

    def forward(self, feat, coarse=None):
        ca = self.channel_att(feat) * feat
        if coarse is None:
            mp = torch.max(feat, dim=1, keepdim=True)[0]
            ap = torch.mean(feat, dim=1, keepdim=True)
            sm = self.spatial_conv(torch.cat([mp, ap], dim=1))
        else:
            sm = F.interpolate(coarse, size=feat.shape[2:], mode='bilinear', align_corners=False)
        return feat * ca * sm


class WeightedFusion(nn.Module):
    def __init__(self, channels):
        super().__init__()
        self.convA = nn.Conv2d(channels, channels, 1)
        self.convB = nn.Conv2d(channels, channels, 1)
        self.weight_conv = nn.Sequential(
            nn.Conv2d(channels*2, channels, 3, padding=1),
            nn.ReLU(True),
            nn.Conv2d(channels, channels, 1),
            nn.Sigmoid()
        )
    def forward(self, A, B):
        a, b = self.convA(A), self.convB(B)
        w = self.weight_conv(torch.cat([a, b], 1))
        return a*w + b*(1-w)


class WDFFNet(nn.Module):
    def __init__(self, pretrained=True, num_classes=1):
        super().__init__()
        self.backA = timm.create_model('efficientnet_b0', pretrained=pretrained,
                                       features_only=True, out_indices=(1,2,3,4))
        self.backB = timm.create_model('resnet50', pretrained=pretrained,
                                       features_only=True, out_indices=(1,2,3,4))

        chsA = self.backA.feature_info.channels()   # [24, 40, 112, 320]
        chsB = self.backB.feature_info.channels()   # [256, 512, 1024, 2048]
        target_chs = [64, 96, 128, 160]

        self.projA = nn.ModuleList([nn.Conv2d(ca, tc, 1) for ca, tc in zip(chsA, target_chs)])
        self.projB = nn.ModuleList([nn.Conv2d(cb, tc, 1) for cb, tc in zip(chsB, target_chs)])

        self.fusions = nn.ModuleList([WeightedFusion(tc) for tc in target_chs])
        self.oams    = nn.ModuleList([ObjectAwareAttention(tc) for tc in target_chs])

        # Decoder
        self.up3 = nn.ConvTranspose2d(160, 128, 2, stride=2)
        self.up2 = nn.ConvTranspose2d(128, 96, 2, stride=2)
        self.up1 = nn.ConvTranspose2d(96, 64, 2, stride=2)

        self.dec_conv3 = nn.Sequential(
            nn.Conv2d(128+128, 128, 3, padding=1),
            nn.ReLU(True)
        )
        self.dec_conv2 = nn.Sequential(
            nn.Conv2d(96+96, 96, 3, padding=1),
            nn.ReLU(True)
        )
        self.dec_conv1 = nn.Sequential(
            nn.Conv2d(64+64, 64, 3, padding=1),
            nn.ReLU(True)
        )

        # FINAL output only at the end
        self.out_conv = nn.Conv2d(64, num_classes, 1)

    def forward(self, x):
        featsA, featsB = self.backA(x), self.backB(x)
        fused = []

        # Encoder: remove coarse prediction
        for pa, pb, fa, fb, fus, oam in zip(self.projA, self.projB, featsA, featsB, self.fusions, self.oams):
            f = fus(pa(fa), pb(fb))
            f = oam(f, None)          # no coarse guidance
            fused.append(f)

        f1, f2, f3, f4 = fused  # shallow → deep

        # Decoder
        u3 = self.up3(f4)
        d3 = self.dec_conv3(torch.cat([u3, f3], 1))

        u2 = self.up2(d3)
        d2 = self.dec_conv2(torch.cat([u2, f2], 1))

        u1 = self.up1(d2)
        d1 = self.dec_conv1(torch.cat([u1, f1], 1))

        return torch.sigmoid(self.out_conv(d1))

!mkdir -p /content/data
!wget -q --no-check-certificate https://datasets.simula.no/downloads/kvasir-seg.zip -O /content/data/kvasir-seg.zip
!unzip -qq -o /content/data/kvasir-seg.zip -d /content/data/

DATA_DIR = '/content/data/Kvasir-SEG'
image_paths = sorted(glob(os.path.join(DATA_DIR, 'images', '*.jpg')))
mask_paths  = sorted(glob(os.path.join(DATA_DIR, 'masks', '*.jpg')))
if len(mask_paths) == 0:
    mask_paths = sorted(glob(os.path.join(DATA_DIR, 'masks', '*.png')))

assert len(image_paths) == len(mask_paths), "Mismatch images/masks"

df = pd.DataFrame({'image': image_paths, 'mask': mask_paths}).sample(frac=1, random_state=42).reset_index(drop=True)
valid_df = df.sample(frac=0.1, random_state=42).reset_index(drop=True)
train_df = df.drop(valid_df.index).reset_index(drop=True)

print(f"✅ Train: {len(train_df)}, Val: {len(valid_df)}")

# Dataloaders
size = 512
batch_size = 4
train_ds = KvasirDataset(train_df, size=size, augment=True)
val_ds   = KvasirDataset(valid_df, size=size, augment=False)
train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, num_workers=2, pin_memory=True)
val_loader   = DataLoader(val_ds, batch_size=batch_size, shuffle=False, num_workers=2, pin_memory=True)

# Model
model = WDFFNet(pretrained=True, num_classes=1).to(DEVICE)

class DiceBCELoss(nn.Module):
    def __init__(self): super().__init__(); self.bce = nn.BCELoss()
    def forward(self, pred, target):
        bce = self.bce(pred, target)
        inter = (pred*target).sum()
        dice = (2*inter + 1e-6) / (pred.sum() + target.sum() + 1e-6)
        return bce + (1 - dice)

criterion = DiceBCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
print("✅ Model ready.")

import numpy as np
from tqdm import tqdm

def dice(p,g): inter=(p*g).sum(); return (2*inter+1e-6)/(p.sum()+g.sum()+1e-6)
def iou(p,g): inter=(p*g).sum(); union=p.sum()+g.sum()-inter; return (inter+1e-6)/(union+1e-6)
def pixel_acc(p,g): return (p==g).float().mean()
def sens(p,g): tp=((p==1)&(g==1)).sum(); fn=((p==0)&(g==1)).sum(); return (tp+1e-6)/(tp+fn+1e-6)
def spec(p,g): tn=((p==0)&(g==0)).sum(); fp=((p==1)&(g==0)).sum(); return (tn+1e-6)/(tn+fp+1e-6)

EPOCHS = 50
best = 0.0
history = {k:[] for k in ["epoch","train_loss","val_dice","val_iou","val_acc","val_sens","val_spec"]}

for ep in range(1, EPOCHS+1):
    model.train()
    run_loss = 0.0
    for imgs, masks in tqdm(train_loader, desc=f"Epoch {ep}/{EPOCHS} - Train"):
        imgs, masks = imgs.to(DEVICE), masks.to(DEVICE)
        optimizer.zero_grad()
        out = model(imgs)
        if out.shape != masks.shape:
            out = F.interpolate(out, size=masks.shape[2:], mode='bilinear', align_corners=False)
        loss = criterion(out, masks)
        loss.backward()
        optimizer.step()
        run_loss += loss.item()
    train_loss = run_loss / len(train_loader)

    # Validation
    model.eval()
    dices, ious, accs, senss, specs = [], [], [], [], []
    with torch.no_grad():
        for imgs, masks in tqdm(val_loader, desc=f"Epoch {ep}/{EPOCHS} - Val"):
            imgs, masks = imgs.to(DEVICE), masks.to(DEVICE)
            out = model(imgs)
            out = F.interpolate(out, size=masks.shape[2:], mode='bilinear', align_corners=False)
            preds = (out > 0.5).float()
            for p,g in zip(preds, masks):
                dices.append(dice(p,g).item())
                ious.append(iou(p,g).item())
                accs.append(pixel_acc(p,g).item())
                senss.append(sens(p,g).item())
                specs.append(spec(p,g).item())

    vd, vi, va, vsn, vsp = np.mean(dices), np.mean(ious), np.mean(accs), np.mean(senss), np.mean(specs)
    history["epoch"].append(ep); history["train_loss"].append(train_loss)
    history["val_dice"].append(vd); history["val_iou"].append(vi)
    history["val_acc"].append(va); history["val_sens"].append(vsn); history["val_spec"].append(vsp)

    print(f"✅ Epoch {ep} | Loss {train_loss:.4f} | Dice {vd:.4f} | IoU {vi:.4f} | Acc {va:.4f} | Sens {vsn:.4f} | Spec {vsp:.4f}")

    if vd > best:
        best = vd
        torch.save(model.state_dict(), "/content/best_wdffnet_full.pth")
        print(f"💾 Saved best model (Dice={best:.4f})")

out_dir = "/content/drive/MyDrive/BalkuProject_Outputs/WDFFNet_FullMetrics"
os.makedirs(out_dir, exist_ok=True)

df_hist = pd.DataFrame(history)
df_hist.to_csv(os.path.join(out_dir, "wdffnet_metrics.csv"), index=False)
print("📊 Metrics saved to Drive:", os.path.join(out_dir, "wdffnet_metrics.csv"))

# ------------------------------------------------------------
# 🔄 De-normalization for correct visualization
# ------------------------------------------------------------
def denormalize(img):
    # Albumentations Normalize() uses ImageNet mean/std
    mean = np.array([0.485, 0.456, 0.406])
    std  = np.array([0.229, 0.224, 0.225])

    img = img.transpose(1, 2, 0)     # CHW → HWC
    img = (img * std) + mean         # Reverse normalization
    img = np.clip(img * 255, 0, 255).astype(np.uint8)
    return img


# ------------------------------------------------------------
# 🖼️ Prediction + Visualization + Saving
# ------------------------------------------------------------
model.load_state_dict(torch.load("/content/best_wdffnet_full.pth", map_location=DEVICE))
model.eval()

save_dir = os.path.join(out_dir, "Predictions")
os.makedirs(save_dir, exist_ok=True)

for i in random.sample(range(len(val_ds)), min(3, len(val_ds))):
    img_t, mask_t = val_ds[i]
    x = img_t.unsqueeze(0).to(DEVICE)

    with torch.no_grad():
        y = model(x)
        y = F.interpolate(y, size=mask_t.shape[1:], mode='bilinear', align_corners=False)
        y = (y > 0.5).float()[0][0].cpu().numpy()

    # -----------------------------
    # FIXED ✔: Properly restored original image
    # -----------------------------
    img_np = denormalize(img_t.numpy())

    mask_np = (mask_t.numpy()[0] * 255).astype(np.uint8)

    fig, ax = plt.subplots(1, 3, figsize=(12, 4))
    ax[0].imshow(img_np); ax[0].set_title("Image"); ax[0].axis('off')
    ax[1].imshow(mask_np, cmap='gray'); ax[1].set_title("GT"); ax[1].axis('off')
    ax[2].imshow(y, cmap='gray'); ax[2].set_title("Pred"); ax[2].axis('off')

    save_path = os.path.join(save_dir, f"wdff_pred_{i}.png")
    plt.savefig(save_path, bbox_inches='tight', dpi=150)
    plt.close()

    print("🖼️ Saved:", save_path)

