# -*- coding: utf-8 -*-
"""Kvasir_SEGPolyp_Transfuse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B2Kf6bImXA_O3e_5Bn0-wyVY-dm401IK
"""

!pip install -q timm albumentations segmentation-models-pytorch==0.3.0 torchmetrics scipy

import os, cv2, numpy as np, pandas as pd, random
import matplotlib.pyplot as plt
from glob import glob
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import albumentations as A
import timm
from tqdm import tqdm

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("🚀 Using device:", DEVICE)

!mkdir -p /content/data
!wget --no-check-certificate https://datasets.simula.no/downloads/kvasir-seg.zip -O /content/data/kvasir-seg.zip
!unzip -qq -o /content/data/kvasir-seg.zip -d /content/data/

DATA_DIR = "/content/data/Kvasir-SEG"
image_paths = sorted(glob(f"{DATA_DIR}/images/*.jpg"))
mask_paths  = sorted(glob(f"{DATA_DIR}/masks/*.jpg"))

assert len(image_paths) == len(mask_paths), "❌ Image/mask count mismatch!"

df = pd.DataFrame({"image": image_paths, "mask": mask_paths}).sample(frac=1, random_state=42).reset_index(drop=True)

valid_df = df.sample(frac=0.1, random_state=42)
train_df = df.drop(valid_df.index)

print(f"✅ Dataset ready | Train: {len(train_df)} | Val: {len(valid_df)}")
print(df.head())

class KvasirDataset(Dataset):
    def __init__(self, df, augment=False, size=224):
        self.df = df.reset_index(drop=True)
        self.size = size
        self.augment = augment

        if augment:
            self.transform = A.Compose([
                A.Resize(self.size, self.size),
                A.HorizontalFlip(p=0.5),
                A.VerticalFlip(p=0.5),
                A.RandomRotate90(p=0.5),
                A.Normalize()
            ])
        else:
            self.transform = A.Compose([
                A.Resize(self.size, self.size),
                A.Normalize()
            ])

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img_path = row["image"]
        mask_path = row["mask"]

        img = cv2.cvtColor(cv2.imread(img_path), cv2.COLOR_BGR2RGB)
        mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
        mask = np.expand_dims(mask, -1)

        data = self.transform(image=img, mask=mask)
        img, mask = data["image"], data["mask"]

        img = np.transpose(img, (2, 0, 1)).astype("float32")
        mask = np.transpose(mask, (2, 0, 1)).astype("float32") / 255.0
        return torch.tensor(img), torch.tensor(mask)

class BiFusionBlock(nn.Module):
    def __init__(self, cnn_ch, trans_ch, out_ch):
        super().__init__()
        self.conv_cnn = nn.Conv2d(cnn_ch, out_ch, 1)
        self.conv_trans = nn.Conv2d(trans_ch, out_ch, 1)
        self.conv_out = nn.Conv2d(out_ch, out_ch, 3, padding=1)
        self.act = nn.ReLU(inplace=True)

    def forward(self, cnn_feat, trans_feat):
        # ✅ Ensure transformer feature is [B, C, H, W]
        if trans_feat.ndim == 4 and trans_feat.shape[1] < 10:
            trans_feat = trans_feat.permute(0, 3, 1, 2)

        c = self.conv_cnn(cnn_feat)
        t = self.conv_trans(trans_feat)

        x = c + t
        x = self.act(self.conv_out(x))

        return x


class TransFuseSimple(nn.Module):
    def __init__(self, num_classes=1, pretrained=True):
        super().__init__()
        self.cnn = timm.create_model("efficientnet_b0", pretrained=pretrained, features_only=True)
        self.trans = timm.create_model("mobilenetv3_large_100", pretrained=pretrained, features_only=True)

        cnn_chs = self.cnn.feature_info.channels()
        trans_chs = self.trans.feature_info.channels()

        self.fuse3 = BiFusionBlock(cnn_chs[-1], trans_chs[-1], 256)
        self.fuse2 = BiFusionBlock(cnn_chs[-2], trans_chs[-2], 128)
        self.fuse1 = BiFusionBlock(cnn_chs[-3], trans_chs[-3], 64)

        self.conv_final = nn.Conv2d(64 + 128 + 256, num_classes, 1)

    def forward(self, x):
        cnn_feats = self.cnn(x)
        trans_feats = self.trans(x)

        # 🔥 FIX ALL transformer features (CORRECT LOCATION)
        fixed_trans_feats = []
        for t in trans_feats:
            if t.ndim == 4 and t.shape[-1] > t.shape[1]:
                t = t.permute(0, 3, 1, 2)
            fixed_trans_feats.append(t)

        trans_feats = fixed_trans_feats

        # 🔥 FUSION
        f3 = self.fuse3(cnn_feats[-1], trans_feats[-1])
        f2 = self.fuse2(cnn_feats[-2], trans_feats[-2])
        f1 = self.fuse1(cnn_feats[-3], trans_feats[-3])

        f3_up = F.interpolate(f3, size=f1.shape[2:], mode="bilinear", align_corners=False)
        f2_up = F.interpolate(f2, size=f1.shape[2:], mode="bilinear", align_corners=False)

        cat = torch.cat([f3_up, f2_up, f1], dim=1)
        out = self.conv_final(cat)

        return torch.sigmoid(out)

size = 224
batch_size = 8

train_ds = KvasirDataset(train_df, augment=True, size=size)
val_ds   = KvasirDataset(valid_df, augment=False, size=size)

train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, num_workers=2)
val_loader   = DataLoader(val_ds, batch_size=batch_size, shuffle=False, num_workers=2)

model = TransFuseSimple(num_classes=1, pretrained=True).to(DEVICE)

class DiceBCELoss(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, preds, targets):
        bce = F.binary_cross_entropy(preds, targets)
        preds_flat = preds.view(-1)
        targets_flat = targets.view(-1)
        inter = (preds_flat * targets_flat).sum()
        dice = (2 * inter + 1e-6) / (preds_flat.sum() + targets_flat.sum() + 1e-6)
        return bce + (1 - dice)

criterion = DiceBCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

# =====================================================
# 🏋️ TransFuse Training Loop — Final Fixed Version (Resolves size mismatch)
# =====================================================

def dice(pred, mask):
    pred = pred.reshape(-1)
    mask = mask.reshape(-1)
    inter = (pred * mask).sum()
    return (2*inter + 1e-6) / (pred.sum() + mask.sum() + 1e-6)

def iou(pred, mask):
    pred = pred.reshape(-1)
    mask = mask.reshape(-1)
    inter = (pred * mask).sum()
    union = pred.sum() + mask.sum() - inter
    return (inter + 1e-6) / (union + 1e-6)

def pixel_accuracy(pred, mask):
    return (pred == mask).float().mean()

def sensitivity(pred, mask):
    tp = ((pred == 1) & (mask == 1)).sum()
    fn = ((pred == 0) & (mask == 1)).sum()
    return (tp + 1e-6) / (tp + fn + 1e-6)

def specificity(pred, mask):
    tn = ((pred == 0) & (mask == 0)).sum()
    fp = ((pred == 0) & (mask == 1)).sum()
    return (tn + 1e-6) / (tn + fp + 1e-6)


EPOCHS = 50
best_val_dice = 0.0
history = {k: [] for k in ["epoch", "train_loss", "val_dice", "val_iou", "val_pixel_acc", "val_sensitivity", "val_specificity"]}

for ep in range(1, EPOCHS + 1):
    model.train()
    running_loss = 0.0
    for imgs, masks in tqdm(train_loader, desc=f"Epoch {ep}/{EPOCHS}"):
        imgs, masks = imgs.to(DEVICE), masks.to(DEVICE)
        optimizer.zero_grad()

        preds = model(imgs)

        # ✅ Resize predictions to match mask shape (solves 28x28 vs 224x224)
        if preds.shape[2:] != masks.shape[2:]:
            preds = F.interpolate(preds, size=masks.shape[2:], mode="bilinear", align_corners=False)

        loss = criterion(preds, masks)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()

    train_loss = running_loss / len(train_loader)

    # --- Validation ---
    model.eval()
    dices, ious, accs, sens, specs = [], [], [], [], []
    with torch.no_grad():
        for imgs, masks in val_loader:
            imgs, masks = imgs.to(DEVICE), masks.to(DEVICE)
            preds = model(imgs)

            # ✅ Match output size again
            if preds.shape[2:] != masks.shape[2:]:
                preds = F.interpolate(preds, size=masks.shape[2:], mode="bilinear", align_corners=False)

            preds = (preds > 0.5).float()

            for p, g in zip(preds, masks):
                dices.append(dice(p, g).item())
                ious.append(iou(p, g).item())
                accs.append(pixel_accuracy(p, g).item())
                sens.append(sensitivity(p, g).item())
                specs.append(specificity(p, g).item())

    val_dice, val_iou = np.mean(dices), np.mean(ious)
    val_acc, val_sens, val_spec = np.mean(accs), np.mean(sens), np.mean(specs)

    history["epoch"].append(ep)
    history["train_loss"].append(train_loss)
    history["val_dice"].append(val_dice)
    history["val_iou"].append(val_iou)
    history["val_pixel_acc"].append(val_acc)
    history["val_sensitivity"].append(val_sens)
    history["val_specificity"].append(val_spec)

    print(f"✅ Epoch {ep:02d} | Loss {train_loss:.4f} | Dice {val_dice:.4f} | IoU {val_iou:.4f}")

    if val_dice > best_val_dice:
        best_val_dice = val_dice
        torch.save(model.state_dict(), "/content/best_transfuse_model_fixed.pth")
        print(f"💾 Saved Best Model (Dice={best_val_dice:.4f})")

print("🏁 Training complete! Best Dice:", best_val_dice)

# =====================================================
# 💾 Save Training Metrics + Predicted Outputs to Drive
# =====================================================

import os, random
import matplotlib.pyplot as plt
import pandas as pd

# ✅ Convert training history to DataFrame
df = pd.DataFrame(history)
metrics_csv_path = "/content/transfuse_training_metrics.csv"
df.to_csv(metrics_csv_path, index=False)
print(f"📊 Metrics saved locally to: {metrics_csv_path}")

# ✅ Mount Google Drive (if not already)
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# ✅ Define Drive directory
drive_dir = "/content/drive/MyDrive/BalkuProject_Outputs/TransFuse_Results"
os.makedirs(drive_dir, exist_ok=True)

# ✅ Copy CSV file to Drive
drive_csv = os.path.join(drive_dir, "transfuse_training_metrics.csv")
df.to_csv(drive_csv, index=False)
print(f"✅ Metrics also saved to: {drive_csv}")

# =====================================================
# 🎨 Save Sample Predictions to Drive
# =====================================================

# Reload best model
model.load_state_dict(torch.load("/content/best_transfuse_model_fixed.pth", map_location=DEVICE))
model.eval()

# Folder for saving images
save_dir = os.path.join(drive_dir, "Predictions")
os.makedirs(save_dir, exist_ok=True)

# Generate and save predictions for random validation samples
n_samples = 5
print(f"🎯 Generating {n_samples} random validation predictions...")

for i in random.sample(range(len(val_ds)), n_samples):
    img, mask = val_ds[i]
    x = img.unsqueeze(0).to(DEVICE)

    with torch.no_grad():
        pred = model(x)
        pred = F.interpolate(pred, size=mask.shape[1:], mode="bilinear", align_corners=False)
        pred = (pred > 0.5).float()[0][0].cpu().numpy()

    fig, ax = plt.subplots(1, 3, figsize=(12, 4))
    ax[0].imshow(np.transpose(img, (1, 2, 0))); ax[0].set_title("Original Image"); ax[0].axis('off')
    ax[1].imshow(mask[0], cmap="gray"); ax[1].set_title("Ground Truth"); ax[1].axis('off')
    ax[2].imshow(pred, cmap="gray"); ax[2].set_title("Predicted Mask"); ax[2].axis('off')

    # Save to Drive
    save_path = os.path.join(save_dir, f"transfuse_prediction_{i+1}.png")
    plt.savefig(save_path, bbox_inches="tight", dpi=150)
    plt.close(fig)

    print(f"🖼️ Saved prediction: {save_path}")

print(f"✅ All predictions saved under: {save_dir}")
print("🚀 TransFuse full workflow complete.")

!pip install -q timm albumentations segmentation-models-pytorch==0.3.0 torchmetrics scipy

import os, cv2, numpy as np, pandas as pd, random
import matplotlib.pyplot as plt
from glob import glob
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import albumentations as A
import timm
from tqdm import tqdm

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("🚀 Using device:", DEVICE)

!mkdir -p /content/data
!wget --no-check-certificate https://datasets.simula.no/downloads/kvasir-seg.zip -O /content/data/kvasir-seg.zip
!unzip -qq -o /content/data/kvasir-seg.zip -d /content/data/

DATA_DIR = "/content/data/Kvasir-SEG"
image_paths = sorted(glob(f"{DATA_DIR}/images/*.jpg"))
mask_paths  = sorted(glob(f"{DATA_DIR}/masks/*.jpg"))

assert len(image_paths) == len(mask_paths), "❌ Image/mask count mismatch!"

df = pd.DataFrame({"image": image_paths, "mask": mask_paths}).sample(frac=1, random_state=42).reset_index(drop=True)

valid_df = df.sample(frac=0.1, random_state=42)
train_df = df.drop(valid_df.index)

print(f"✅ Dataset ready | Train: {len(train_df)} | Val: {len(valid_df)}")
print(df.head())

class KvasirDataset(Dataset):
    def __init__(self, df, augment=False, size=224):
        self.df = df.reset_index(drop=True)
        self.size = size
        self.augment = augment

        if augment:
            self.transform = A.Compose([
                A.Resize(self.size, self.size),
                A.HorizontalFlip(p=0.5),
                A.VerticalFlip(p=0.5),
                A.RandomRotate90(p=0.5),
                A.Normalize()
            ])
        else:
            self.transform = A.Compose([
                A.Resize(self.size, self.size),
                A.Normalize()
            ])

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img_path = row["image"]
        mask_path = row["mask"]

        img = cv2.cvtColor(cv2.imread(img_path), cv2.COLOR_BGR2RGB)
        mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
        mask = np.expand_dims(mask, -1)

        data = self.transform(image=img, mask=mask)
        img, mask = data["image"], data["mask"]

        img = np.transpose(img, (2, 0, 1)).astype("float32")
        mask = np.transpose(mask, (2, 0, 1)).astype("float32") / 255.0
        return torch.tensor(img), torch.tensor(mask)

class BiFusionBlock(nn.Module):
    def __init__(self, cnn_ch, trans_ch, out_ch):
        super().__init__()
        self.conv_cnn = nn.Conv2d(cnn_ch, out_ch, 1)
        self.conv_trans = nn.Conv2d(trans_ch, out_ch, 1)
        self.conv_out = nn.Conv2d(out_ch, out_ch, 3, padding=1)
        self.act = nn.ReLU(inplace=True)

    def forward(self, cnn_feat, trans_feat):
        # ✅ Ensure transformer feature is [B, C, H, W]
        if trans_feat.ndim == 4 and trans_feat.shape[1] < 10:
            trans_feat = trans_feat.permute(0, 3, 1, 2)

        c = self.conv_cnn(cnn_feat)
        t = self.conv_trans(trans_feat)

        x = c + t
        x = self.act(self.conv_out(x))

        return x


class TransFuseSimple(nn.Module):
    def __init__(self, num_classes=1, pretrained=True):
        super().__init__()
        self.cnn = timm.create_model("efficientnet_b0", pretrained=pretrained, features_only=True)
        self.trans = timm.create_model("mobilenetv3_large_100", pretrained=pretrained, features_only=True)

        cnn_chs = self.cnn.feature_info.channels()
        trans_chs = self.trans.feature_info.channels()

        self.fuse3 = BiFusionBlock(cnn_chs[-1], trans_chs[-1], 256)
        self.fuse2 = BiFusionBlock(cnn_chs[-2], trans_chs[-2], 128)
        self.fuse1 = BiFusionBlock(cnn_chs[-3], trans_chs[-3], 64)

        self.conv_final = nn.Conv2d(64 + 128 + 256, num_classes, 1)

    def forward(self, x):
        cnn_feats = self.cnn(x)
        trans_feats = self.trans(x)

        # 🔥 FIX ALL transformer features (CORRECT LOCATION)
        fixed_trans_feats = []
        for t in trans_feats:
            if t.ndim == 4 and t.shape[-1] > t.shape[1]:
                t = t.permute(0, 3, 1, 2)
            fixed_trans_feats.append(t)

        trans_feats = fixed_trans_feats

        # 🔥 FUSION
        f3 = self.fuse3(cnn_feats[-1], trans_feats[-1])
        f2 = self.fuse2(cnn_feats[-2], trans_feats[-2])
        f1 = self.fuse1(cnn_feats[-3], trans_feats[-3])

        f3_up = F.interpolate(f3, size=f1.shape[2:], mode="bilinear", align_corners=False)
        f2_up = F.interpolate(f2, size=f1.shape[2:], mode="bilinear", align_corners=False)

        cat = torch.cat([f3_up, f2_up, f1], dim=1)
        out = self.conv_final(cat)

        return torch.sigmoid(out)

size = 224
batch_size = 8

train_ds = KvasirDataset(train_df, augment=True, size=size)
val_ds   = KvasirDataset(valid_df, augment=False, size=size)

train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, num_workers=2)
val_loader   = DataLoader(val_ds, batch_size=batch_size, shuffle=False, num_workers=2)

model = TransFuseSimple(num_classes=1, pretrained=True).to(DEVICE)

class DiceBCELoss(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, preds, targets):
        bce = F.binary_cross_entropy(preds, targets)
        preds_flat = preds.view(-1)
        targets_flat = targets.view(-1)
        inter = (preds_flat * targets_flat).sum()
        dice = (2 * inter + 1e-6) / (preds_flat.sum() + targets_flat.sum() + 1e-6)
        return bce + (1 - dice)

criterion = DiceBCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

# =====================================================
# 🏋️ TransFuse Training Loop — Final Fixed Version (Resolves size mismatch)
# =====================================================

def dice(pred, mask):
    pred = pred.reshape(-1)
    mask = mask.reshape(-1)
    inter = (pred * mask).sum()
    return (2*inter + 1e-6) / (pred.sum() + mask.sum() + 1e-6)

def iou(pred, mask):
    pred = pred.reshape(-1)
    mask = mask.reshape(-1)
    inter = (pred * mask).sum()
    union = pred.sum() + mask.sum() - inter
    return (inter + 1e-6) / (union + 1e-6)

def pixel_accuracy(pred, mask):
    return (pred == mask).float().mean()

def sensitivity(pred, mask):
    tp = ((pred == 1) & (mask == 1)).sum()
    fn = ((pred == 0) & (mask == 1)).sum()
    return (tp + 1e-6) / (tp + fn + 1e-6)

def specificity(pred, mask):
    tn = ((pred == 0) & (mask == 0)).sum()
    fp = ((pred == 0) & (mask == 1)).sum()
    return (tn + 1e-6) / (tn + fp + 1e-6)


EPOCHS = 50
best_val_dice = 0.0
history = {k: [] for k in ["epoch", "train_loss", "val_dice", "val_iou", "val_pixel_acc", "val_sensitivity", "val_specificity"]}

for ep in range(1, EPOCHS + 1):
    model.train()
    running_loss = 0.0
    for imgs, masks in tqdm(train_loader, desc=f"Epoch {ep}/{EPOCHS}"):
        imgs, masks = imgs.to(DEVICE), masks.to(DEVICE)
        optimizer.zero_grad()

        preds = model(imgs)

        # ✅ Resize predictions to match mask shape (solves 28x28 vs 224x224)
        if preds.shape[2:] != masks.shape[2:]:
            preds = F.interpolate(preds, size=masks.shape[2:], mode="bilinear", align_corners=False)

        loss = criterion(preds, masks)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()

    train_loss = running_loss / len(train_loader)

    # --- Validation ---
    model.eval()
    dices, ious, accs, sens, specs = [], [], [], [], []
    with torch.no_grad():
        for imgs, masks in val_loader:
            imgs, masks = imgs.to(DEVICE), masks.to(DEVICE)
            preds = model(imgs)

            # ✅ Match output size again
            if preds.shape[2:] != masks.shape[2:]:
                preds = F.interpolate(preds, size=masks.shape[2:], mode="bilinear", align_corners=False)

            preds = (preds > 0.5).float()

            for p, g in zip(preds, masks):
                dices.append(dice(p, g).item())
                ious.append(iou(p, g).item())
                accs.append(pixel_accuracy(p, g).item())
                sens.append(sensitivity(p, g).item())
                specs.append(specificity(p, g).item())

    val_dice, val_iou = np.mean(dices), np.mean(ious)
    val_acc, val_sens, val_spec = np.mean(accs), np.mean(sens), np.mean(specs)

    history["epoch"].append(ep)
    history["train_loss"].append(train_loss)
    history["val_dice"].append(val_dice)
    history["val_iou"].append(val_iou)
    history["val_pixel_acc"].append(val_acc)
    history["val_sensitivity"].append(val_sens)
    history["val_specificity"].append(val_spec)

    print(f"✅ Epoch {ep:02d} | Loss {train_loss:.4f} | Dice {val_dice:.4f} | IoU {val_iou:.4f}")

    if val_dice > best_val_dice:
        best_val_dice = val_dice
        torch.save(model.state_dict(), "/content/best_transfuse_model_fixed.pth")
        print(f"💾 Saved Best Model (Dice={best_val_dice:.4f})")

print("🏁 Training complete! Best Dice:", best_val_dice)

# =====================================================
# 💾 Save Training Metrics + Predicted Outputs to Drive
# =====================================================

import os, random
import matplotlib.pyplot as plt
import pandas as pd

# ✅ Convert training history to DataFrame
df = pd.DataFrame(history)
metrics_csv_path = "/content/transfuse_training_metrics.csv"
df.to_csv(metrics_csv_path, index=False)
print(f"📊 Metrics saved locally to: {metrics_csv_path}")

# ✅ Mount Google Drive (if not already)
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# ✅ Define Drive directory
drive_dir = "/content/drive/MyDrive/BalkuProject_Outputs/TransFuse_Results"
os.makedirs(drive_dir, exist_ok=True)

# ✅ Copy CSV file to Drive
drive_csv = os.path.join(drive_dir, "transfuse_training_metrics.csv")
df.to_csv(drive_csv, index=False)
print(f"✅ Metrics also saved to: {drive_csv}")

# =====================================================
# 🎨 Save Sample Predictions to Drive
# =====================================================

# Reload best model
model.load_state_dict(torch.load("/content/best_transfuse_model_fixed.pth", map_location=DEVICE))
model.eval()

# Folder for saving images
save_dir = os.path.join(drive_dir, "Predictions")
os.makedirs(save_dir, exist_ok=True)

# Generate and save predictions for random validation samples
n_samples = 5
print(f"🎯 Generating {n_samples} random validation predictions...")

for i in random.sample(range(len(val_ds)), n_samples):
    img, mask = val_ds[i]
    x = img.unsqueeze(0).to(DEVICE)

    with torch.no_grad():
        pred = model(x)
        pred = F.interpolate(pred, size=mask.shape[1:], mode="bilinear", align_corners=False)
        pred = (pred > 0.5).float()[0][0].cpu().numpy()

    fig, ax = plt.subplots(1, 3, figsize=(12, 4))
    ax[0].imshow(np.transpose(img, (1, 2, 0))); ax[0].set_title("Original Image"); ax[0].axis('off')
    ax[1].imshow(mask[0], cmap="gray"); ax[1].set_title("Ground Truth"); ax[1].axis('off')
    ax[2].imshow(pred, cmap="gray"); ax[2].set_title("Predicted Mask"); ax[2].axis('off')

    # Save to Drive
    save_path = os.path.join(save_dir, f"transfuse_prediction_{i+1}.png")
    plt.savefig(save_path, bbox_inches="tight", dpi=150)
    plt.close(fig)

    print(f"🖼️ Saved prediction: {save_path}")

print(f"✅ All predictions saved under: {save_dir}")
print("🚀 TransFuse full workflow complete.")