# -*- coding: utf-8 -*-
"""RESUNet++_Kvasir.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BvraLchvP0_7r0sbviE9dc58niENFMhF
"""

# 🧠 Install PyTorch and key libs
!pip install -q -U torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
!pip install -q -U segmentation-models-pytorch albumentations timm tqdm matplotlib scikit-learn opencv-python

# 🧠 Clone ResUNet++ repository
!git clone https://github.com/DebeshJha/ResUNetPlusPlus.git /content/ResUNetPlusPlus

# ✅ Fix pandas version for Colab compatibility
!pip install -q pandas==2.2.2

# 🧩 Add repo to Python path
import sys
sys.path.append("/content/ResUNetPlusPlus")

!mkdir -p /content/data
!wget --no-check-certificate https://datasets.simula.no/downloads/kvasir-seg.zip -O /content/data/kvasir-seg.zip
!unzip -qq -o /content/data/kvasir-seg.zip -d /content/data/

import os, cv2, numpy as np, pandas as pd
from glob import glob
from sklearn.model_selection import train_test_split

DATA_DIR = '/content/data/Kvasir-SEG'
image_paths = sorted(glob(os.path.join(DATA_DIR, 'images', '*.jpg')))
mask_paths  = sorted(glob(os.path.join(DATA_DIR, 'masks',  '*.jpg')))

assert len(image_paths) == len(mask_paths), "Mismatch between images and masks!"

df = pd.DataFrame({'image': image_paths, 'mask': mask_paths}).sample(frac=1, random_state=42).reset_index(drop=True)
valid_df = df.sample(frac=0.1, random_state=42)
train_df = df.drop(valid_df.index).reset_index(drop=True)
train_df, val_df = train_test_split(train_df, test_size=0.2, random_state=42)

print(f"Train: {len(train_df)}, Val: {len(val_df)}, Holdout: {len(valid_df)}")

from torch.utils.data import Dataset, DataLoader
import albumentations as A
import segmentation_models_pytorch as smp

class KvasirDataset(Dataset):
    def __init__(self, df, aug=None, prep=None):
        self.df = df.reset_index(drop=True)
        self.aug = aug
        self.prep = prep

    def __len__(self): return len(self.df)

    def __getitem__(self, idx):
        img = cv2.cvtColor(cv2.imread(self.df.iloc[idx,0]), cv2.COLOR_BGR2RGB)
        mask = cv2.imread(self.df.iloc[idx,1], cv2.IMREAD_GRAYSCALE)
        mask = (mask > 127).astype("float32")
        mask = np.expand_dims(mask, axis=-1)

        if self.aug:
            data = self.aug(image=img, mask=mask)
            img, mask = data["image"], data["mask"]

        if self.prep:
            data = self.prep(image=img, mask=mask)
            img, mask = data["image"], data["mask"]

        return img, mask

def aug_train():
    return A.Compose([
        A.Resize(512,512),
        A.HorizontalFlip(),
        A.VerticalFlip(),
        A.RandomRotate90(p=0.5),
    ])

def aug_val():
    return A.Compose([A.Resize(512,512)])

prep_fn = smp.encoders.get_preprocessing_fn("resnet50", "imagenet")
def prep():
    return A.Compose([
        A.Lambda(image=prep_fn),
        A.Lambda(
            image=lambda x, **k: x.transpose(2,0,1).astype("float32"),
            mask=lambda x, **k: x.transpose(2,0,1).astype("float32")
        ),
    ])

train_ds = KvasirDataset(train_df, aug_train(), prep())
val_ds   = KvasirDataset(val_df, aug_val(), prep())
holdout_ds = KvasirDataset(valid_df, aug_val(), prep())

train_loader = DataLoader(train_ds, batch_size=4, shuffle=True, num_workers=2)
val_loader   = DataLoader(val_ds, batch_size=4, shuffle=False, num_workers=2)
holdout_loader = DataLoader(holdout_ds, batch_size=4, shuffle=False, num_workers=2)

print("✅ Data loaders ready!")

!grep -n "class " /content/ResUNetPlusPlus/resunet++_pytorch.py

!grep -A 10 "class build_resunetplusplus" /content/ResUNetPlusPlus/resunet++_pytorch.py

import torch, importlib.util

# ✅ Load the ResUNet++ file safely
spec = importlib.util.spec_from_file_location(
    "resunetplusplus", "/content/ResUNetPlusPlus/resunet++_pytorch.py"
)
resunet_module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(resunet_module)

# ✅ Use the correct class
ResUnetPlusPlus = resunet_module.build_resunetplusplus

# ✅ Initialize (no args, since it’s hard-coded for 3 → 1 channels)
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
model = ResUnetPlusPlus().to(DEVICE)

print("✅ ResUNet++ model initialized successfully on:", DEVICE)

# ✅ Optional sanity check
dummy = torch.randn(1, 3, 512, 512).to(DEVICE)
out = model(dummy)
print("Output shape:", tuple(out.shape))

import torch.nn.functional as F
import numpy as np

dice_loss = smp.losses.DiceLoss(mode="binary")
bce_loss  = smp.losses.SoftBCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

# ----- Metric functions (your requested full set) -----
def dice(pred, mask):
    pred = pred.reshape(-1)
    mask = mask.reshape(-1)
    inter = (pred * mask).sum()
    return (2*inter + 1e-6) / (pred.sum() + mask.sum() + 1e-6)

def iou(pred, mask):
    pred = pred.reshape(-1)
    mask = mask.reshape(-1)
    inter = (pred * mask).sum()
    union = pred.sum() + mask.sum() - inter
    return (inter + 1e-6) / (union + 1e-6)

def pixel_accuracy(pred, mask):
    pred = pred.reshape(-1)
    mask = mask.reshape(-1)
    correct = (pred == mask).sum()
    total = mask.numel()
    return correct.float() / total

def sensitivity(pred, mask):
    pred = pred.reshape(-1)
    mask = mask.reshape(-1)
    tp = ((pred == 1) & (mask == 1)).sum()
    fn = ((pred == 0) & (mask == 1)).sum()
    return (tp + 1e-6) / (tp + fn + 1e-6)

def specificity(pred, mask):
    pred = pred.reshape(-1)
    mask = mask.reshape(-1)
    tn = ((pred == 0) & (mask == 0)).sum()
    fp = ((pred == 0) & (mask == 1)).sum()
    return (tn + 1e-6) / (tn + fp + 1e-6)

from tqdm.auto import tqdm

EPOCHS = 50
best_val_dice = 0.0
save_path = "/content/best_resunetpp_model.pth"

history = {
    "epoch": [], "train_loss": [],
    "val_dice": [], "val_iou": [], "val_pixel_acc": [],
    "val_sensitivity": [], "val_specificity": []
}

for ep in range(1, EPOCHS + 1):
    model.train()
    epoch_loss = 0
    loop = tqdm(train_loader, desc=f"Epoch {ep}/{EPOCHS}")
    for x, y in loop:
        x, y = x.to(DEVICE), y.to(DEVICE)
        optimizer.zero_grad()
        out = model(x)
        loss = dice_loss(out, y) + bce_loss(out, y)
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()
        loop.set_postfix({"loss": f"{loss.item():.4f}"})
    train_loss = epoch_loss / len(train_loader)

    # ----- Validation -----
    model.eval()
    dices=[]; ious=[]; accs=[]; sens=[]; specs=[]
    with torch.no_grad():
        for x, y in val_loader:
            x, y = x.to(DEVICE), y.to(DEVICE)
            preds = (torch.sigmoid(model(x)) > 0.5).float()
            y_bin = y[:, 0:1, :, :]
            p_bin = preds[:, 0:1, :, :]

            dices.append(dice(p_bin, y_bin).item())
            ious.append(iou(p_bin, y_bin).item())
            accs.append(pixel_accuracy(p_bin, y_bin).item())
            sens.append(sensitivity(p_bin, y_bin).item())
            specs.append(specificity(p_bin, y_bin).item())

    history["epoch"].append(ep)
    history["train_loss"].append(train_loss)
    history["val_dice"].append(np.mean(dices))
    history["val_iou"].append(np.mean(ious))
    history["val_pixel_acc"].append(np.mean(accs))
    history["val_sensitivity"].append(np.mean(sens))
    history["val_specificity"].append(np.mean(specs))

    print(f"✅ Epoch {ep} | Loss {train_loss:.4f} | Dice {np.mean(dices):.4f} | IoU {np.mean(ious):.4f}")

    if np.mean(dices) > best_val_dice:
        best_val_dice = np.mean(dices)
        torch.save(model.state_dict(), save_path)
        print(f"💾 Saved Best Model (Dice: {best_val_dice:.4f})")

from google.colab import drive
import pandas as pd, os, shutil

drive.mount('/content/drive')

df = pd.DataFrame(history)
os.makedirs("/content/drive/MyDrive/BalkuProject_Outputs", exist_ok=True)
df.to_csv("/content/drive/MyDrive/BalkuProject_Outputs/resunetpp_training_metrics.csv", index=False)
shutil.copy(save_path, "/content/drive/MyDrive/BalkuProject_Outputs/best_resunetpp_model.pth")

print("🎯 Training Completed and saved to Drive.")
df.head()

import matplotlib.pyplot as plt, random, os

save_dir = "/content/drive/MyDrive/BalkuProject_Outputs/ResUNetPlusPlus_Predictions"
os.makedirs(save_dir, exist_ok=True)

def predict(x):
    model.eval()
    with torch.no_grad():
        y = model(x.to(DEVICE))
        return (torch.sigmoid(y) > 0.5).float()

def show_results(n=3):
    idxs = random.sample(range(len(val_ds)), n)
    for i, idx in enumerate(idxs):
        img, mask = val_ds[idx]
        x = torch.tensor(img).unsqueeze(0)
        pred = predict(x)[0][0].cpu().numpy()

        fig, ax = plt.subplots(1,3, figsize=(12,4))
        ax[0].imshow(img.transpose(1,2,0)); ax[0].set_title("Image")
        ax[1].imshow(mask[0], cmap='gray'); ax[1].set_title("Ground Truth")
        ax[2].imshow(pred, cmap='gray');    ax[2].set_title("Prediction")
        plt.savefig(os.path.join(save_dir, f"prediction_{i+1}.png"), bbox_inches='tight')
        plt.close(fig)
        print(f"✅ Saved: {save_dir}/prediction_{i+1}.png")

show_results(3)

